services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/crypto-tracker
    depends_on:
      - db
    container_name: mwongess/cryptocurrency-tracker-api

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: cryptocurrency-tracker-db

volumes:
  mongo-data: