name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/my-node-app .

    - name: Push Docker image to Docker Hub
      run: |
        docker push your-dockerhub-username/my-node-app

    - name: SSH into EC2 and deploy Docker container
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Stop and remove the existing container
          docker stop my-node-app || true
          docker rm my-node-app || true
          # Pull the latest Docker image
          docker pull your-dockerhub-username/my-node-app
          # Run the container
          docker run -d -p 80:3000 --name my-node-app your-dockerhub-username/my-node-app
