name: Deploy Node.js App to EC2 Instance

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        run: |
          docker compose build
          docker tag cryptocurrency-tracker-app  mwongess/cryptocurrency-tracker-api:latest
          docker push mwongess/cryptocurrency-tracker-api
      
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Copy .env file
        run: |
          cp /home/ubuntu/actions-runner/.env ./.env

      - name: Pull Docker images
        run: docker compose pull mwongess/cryptocurrency-tracker-api:latest
      
      - name: Stop and remove old containers
        run: docker compose down
      
      - name: Start services with Docker Compose
        run: docker compose up -d 
