name: Deploy Node.js App to EC2 Instance

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t mwongess/cryptocurrency-tracker-app .
      
      - name: Publish image to Docker Hub
        run: docker push mwongess/cryptocurrency-tracker-app:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull mwongess/cryptocurrency-tracker-app:latest
        
      - name: Run Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
